### ISSUE TITLE
프로필 설정 API 구현

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#15]
## Description
온보딩 단계에 필요한 팀 조회, 팀 선택, 프로필 설정 API를 구현합니다.

## Todo
- [x] 팀 조회 API 구현
- [x] 팀 선택 API 구현
- [x] 프로필 설정 API 구현

## ETC
기타사항 입력해주세요.
