### ISSUE TITLE
선물하기 시, 한마디 입력 기능 추가

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#181]
## Description
토큰 선물하기 시, 보내는 상대에게 한마디 입력하는 기능 추가

## Todo
- [ ] gitf_token 테이블 comment 컬럼 추가
- [ ] GiftToken 엔티티 comment 필드 추가
- [ ] MemberService.saveGiftToken 메서드 수정
- [ ] MemberService.findGiftHistories 메서드 수정

## ETC
기타사항 입력해주세요.
