### ISSUE TITLE
월간 승리요정 테스트 코드 작성

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#203]
## Description
월간 승리요정 관련 API에 대한 테스트 코드 작성

## Todo
- [x] 월간 승리요정 리스트 조회 테스트 코드 작성
- [x] 월간 승리요정 댓글 조회 테스트 코드 작성
- [x] 월간 승리요정 대댓글 조회 테스트 코드 작성
- [x] 월간 승리요정 댓글 작성 테스트 코드 작성
- [x] 월간 승리요정 대댓글 작성 테스트 코드 작성
- [x] 월간 승리요정 댓글 삭제 테스트 코드 작성
- [x] 월간 승리요정 댓글 좋아요 테스트 코드 작성
- [x] 월간 승리요정 댓글 좋아요 취소 테스트 코드 작성
- [x] 월간 승리요정 프로필 조회 테스트 코드 작성

## ETC
기타사항 입력해주세요.
