### ISSUE TITLE
마이페이지 테스트 코드 작성

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#204]
## Description
마이페이지 테스트 코드 작성

## Todo
- [x] 마이페이지 프로필 정보 조회 테스트 코드 작성
- [x] 마이페이지 요정 통계 조회 테스트 코드 작성
- [x] 마이페이지 요정 기록 조회 테스트 코드 작성
- [x] 마이페이지 선물내역 조회 테스트 코드 작성

## ETC
기타사항 입력해주세요.
