### ISSUE TITLE
온보딩 단계 테스트 코드 작성

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#205]
## Description
온보딩 단계 테스트 코드 작성

## Todo
- [ ] 로그인 테스트 코드 작성
- [ ] OAuth2 로그인 테스트 코드 작성
- [x] 구단 조회 테스트 코드 작성
- [x] 구단 선택하기 테스트 코드 작성
- [x] 프로필 설정하기 테스트 코드 작성
- [x] 닉네임 중복확인 테스트 코드 작성

## ETC
기타사항 입력해주세요.
