### ISSUE TITLE
오늘의 승부예측 테스트 코드 작성

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#217]
## Description
오늘의 승부예측 테스트 코드 작성

## Todo
- [x] GameService 클래스 테스트 코드 작성
- [x] GameController 클래스 테스트 코드 작성
- [x] GameVoteService 클래스 테스트 코드 작성
- [x] GameVoteController 클래스 테스트 코드 작성

## ETC
기타사항 입력해주세요.
