### ISSUE TITLE
로그인 API 구현

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#7]
## Description
개발 진행기간 동안 테스트를 위해 더미데이터를 이용하여 자체 로그인할 수 있는 API 기능 구현

## Todo
- [x] SecurityConfig 설정
- [x] JWT 토큰 생성 구현
- [x] JWT 토큰 검증 구현
- [x] JWT 필터 구현
- [x] 로그인 기능 구현

## ETC
기타사항 입력해주세요.
