### ISSUE TITLE
비즈니스 로직 예외처리 작업

### ISSUE THREAD

**Issue by seonghye0n** [baseball-project/backend#78]
## Description
비즈니스 로직에서 발생하는 예외에 대한 예외처리 작업

## Todo
- [x] Member 찾을 수 없을 때
- [x] Team 찾을 수 없을 때
- [x] Reply 찾을 수 없을 때 
- [x] 본인이 작성한 댓글만 삭제 가능
- [x] 댓글 좋아요는 한번만 가능
- [x] 프로필 수정 시, 닉네임 중복 방지

## ETC
기타사항 입력해주세요.
